[project]
name = "mcts-forest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[classic-control,other,toy-text]>=1.2.3",
    "gymnax",
    "httpx>=0.28.1",
    "jumanji",
    "matplotlib>=3.10.8",
    "mctx>=0.0.71",
    "moviepy>=2.2.1",
    "numba>=0.65.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "rich>=15.0.0",
    "setuptools<70.0.0",
    "tqdm>=4.67.3",
    "websocket-client>=1.9.0",
]

[tool.uv]
package = true

[tool.uv.sources]
gymnax = { git = "https://github.com/RobertTLange/gymnax.git", rev = "main" }
jumanji = { git = "https://github.com/instadeepai/jumanji.git" }

[project.scripts]
benchmark = "mcts_forest.scripts.benchmark:main"
benchmax = "mcts_forest.scripts.benchmax:main"
remote = "mcts_forest.scripts.remote_kaggle:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
norecursedirs = ["gymcts_original", ".venv", ".git", "results"]
addopts = "--verbose --cov=src --cov-report=term-missing"
